Update the neptune3-ui repository
The neptune3-ui graphic assets are not in the repository that contains the
code but instead have git-lfs pointers. This is not working though for the
repository in code.qt.io and fails with the following error when cloning:

  $ git clone git://code.qt.io/qt-apps/neptune3-ui.git
  Cloning into 'neptune3-ui'...
  remote: Counting objects: 22160, done.
  remote: Compressing objects: 100% (9389/9389), done.
  remote: Total 22160 (delta 14724), reused 18776 (delta 11991)
  Receiving objects: 100% (22160/22160), 7.29 MiB | 5.77 MiB/s, done.
  Resolving deltas: 100% (14724/14724), done.
  Downloading apps/com.luxoft.vehicle/+lucee/icon.png (820 B)
  Error downloading object: apps/com.luxoft.vehicle/+lucee/icon.png (cff47f6): Smudge error: Error downloading apps/com.luxoft.vehicle/+lucee/icon.png (cff47f6c6ba5b27ceeb3fbe1a4aca8e04a572a802eaa9fc518c475c66121a726): batch response: Rep  ository or object not found: https://code.qt.io/qt-apps/neptune3-ui.git/info/lfs/objects/batch
  Check that it exists and that you have proper access to it

  Errors logged to /home/javier/devel/neptune3-ui/.git/lfs/logs/20211028T091853.815142581.log
  Use `git lfs logs last` to view the log.
  error: external filter 'git-lfs filter-process' failed
  fatal: apps/com.luxoft.vehicle/+lucee/icon.png: smudge filter lfs failed
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

Insted of using this broken repo, use the one in codereview.qt-project.org
that's seems to be working correctly.

Not installing images but instead text files containing git-lfs pointers
was the reason why the neptun3-ui didn't render properly. That was fixed
after using this new repository to build and install the neptun3-ui app.

Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>